POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "johndoe@email.com",
    "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNjRVYmZFbkx5cHVSSW1HUlR6SHVNLmRCSmU3M1BuYVJBT2JpNmlBUERzQldaNjYyY2hZd3UiLCJpYXQiOjE3NTM5ODg2NjIsImV4cCI6MTc1Mzk4ODY2M30.mPJ_vHwNhF1PpGA6p9GMrkhmjGDio7xYgWq5XVRJubk

{
    
}
