POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "janedoe@email.com",
    "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVkb2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkalVXcVNRak1ISHFXcVpDaWZ3Z3VqdXJpRE9sUWtVS1NjMDFZRTVEREdjdUYyLnhuU2VFRGEiLCJpYXQiOjE3NTM5ODg5NjMsImV4cCI6MTc1NDA3NTM2M30.BqkyzYTvC9lEFU8lkUrmzuSL-HGmcwo6xjgVTGJL40E

{
    "email": "johndoe@email.com",
    "password": "password"
}

###

PATCH http://localhost:3000/api/increment_app/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNjRVYmZFbkx5cHVSSW1HUlR6SHVNLmRCSmU3M1BuYVJBT2JpNmlBUERzQldaNjYyY2hZd3UiLCJpYXQiOjE3NTM5OTcxNjIsImV4cCI6MTc1NDA4MzU2Mn0.EM11TbB5eVP4l6vklKTHwCKyOcKJ8k2UvjTB5eFeiW0

###

GET http://localhost:3000/api/get_most_frequent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNjRVYmZFbkx5cHVSSW1HUlR6SHVNLmRCSmU3M1BuYVJBT2JpNmlBUERzQldaNjYyY2hZd3UiLCJpYXQiOjE3NTM5OTcxNjIsImV4cCI6MTc1NDA4MzU2Mn0.EM11TbB5eVP4l6vklKTHwCKyOcKJ8k2UvjTB5eFeiW0