POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "janedoe@email.com",
    "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVkb2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkalVXcVNRak1ISHFXcVpDaWZ3Z3VqdXJpRE9sUWtVS1NjMDFZRTVEREdjdUYyLnhuU2VFRGEiLCJpYXQiOjE3NTM5ODg5NjMsImV4cCI6MTc1NDA3NTM2M30.BqkyzYTvC9lEFU8lkUrmzuSL-HGmcwo6xjgVTGJL40E

{
    
}
